# Generated by Django 5.0.7 on 2025-08-28 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='arrendatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alquileres_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alquileres', to='catalog.articulo'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alquileres_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='alquiler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='rentals.alquiler'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_emitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='alquiler',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='rentals.alquiler'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('alquiler', 'autor')},
        ),
    ]
